batch_size: 8
epochs: 80
eval_every_n_epochs: 1
fine_tune_from: None
log_every_n_steps: 1
weight_decay: 10e-6
fp16_precision: False

model:
  out_dim: 2048
  base_model: "resnet50"

dataset:
  s: 1
  input_shape: (256,256,3)
  num_workers: 0
  valid_size: 0.05
  path: "/home/hynek/skola/FEL/5. semestr/SimCLR/DAVIS_train/JPEGImages/480p"

loss:
  temperature: 0.5
  use_cosine_similarity: True
